import { Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: false,
  styleUrl: './app.scss'
})
export class App {
  indiceDaPessoaSelecionada: number | undefined;
  listaPessoas = [
    { nome: "Felipe Freitas", idade: 26},
    { nome: "Zé Merda", idade: 14},
    { nome: "Ôio Junto", idade: 55},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
    { nome: "Joãozinho", idade: 18},
  ];

  selecionarPessoa(indice: number) {
    console.log(indice);
    this.indiceDaPessoaSelecionada = indice;
  }
}